###Recuperar Todos los usuarios
GET http://82.223.120.79:8080/users
Accept: application/json

###Recuperar un Usuario en especifico
GET http://127.0.0.1:8080/users/1
Accept: application/json

###Actualiza el email de un Usuario
PUT http://127.0.0.1:8080/users/3
Content-Type: application/json
Accept: application/json

{
  "email": "perrosanxe@gmail.com"
}


###Elimina un Usuario
DELETE http://127.0.0.1:8080/users/2
Content-Type: application/json
Accept: application/json



###Crea un Usuario
POST http://127.0.0.1:8080/users
Content-Type: application/json
Accept: application/json

{
  "username": "Mariet",
  "password": "admin",
  "fullName": "Mario Benedetto",
  "email": "mario@gmail.com",
  "gender": "Male"
}

